name: CI/CD Pipeline #Name WorkFlow

on: #Trigger/event 
  push: #1
    branches:
      - main
      - develop
      - 'feature/*'
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest #2

    steps:
      - name: Hello World #3
        run: echo "Hello World" #4

  dependencies:
    runs-on: ubuntu-latest #5

    steps:
      - name: Install Dependencies #6
        run: |
          echo "Installing dependencies..."
          # Add commands to install dependencies here
          echo "Dependencies installed."
          echo "add plugins in szh"

    strategy:
      matrix:
        message: ["Hola", "CodigoFacilito", "Bootcamp GitHub Action"]
    
      steps:
      - name: Print mensaje
      run: echo "${{ matrix.message }}"                